
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BOOLEAN COMMA COMMENT DATE DATETIME DOT EQUAL FLOAT IDENTIFIER INTEGER LEFT_BRACE LEFT_BRACKET NEWLINE RIGHT_BRACE RIGHT_BRACKET STRING TIME WHITESPACEtoml : expression NEWLINE expressionexpression : COMMENTexpression : keyval NEWLINEkeyval : IDENTIFIER WHITESPACE EQUAL WHITESPACE value NEWLINEkeyval : IDENTIFIER DOT IDENTIFIER EQUAL valuevalue : STRINGvalue : INTEGERvalue : FLOATvalue : BOOLEANvalue : DATETIMEvalue : DATEvalue : TIME'
    
_lr_action_items = {'COMMENT':([0,6,],[3,3,]),'IDENTIFIER':([0,6,9,],[5,5,12,]),'$end':([1,3,7,10,],[0,-2,-3,-1,]),'NEWLINE':([2,3,4,7,15,16,17,18,19,20,21,22,23,24,],[6,-2,7,-3,24,-6,-7,-8,-9,-10,-11,-12,-5,-4,]),'WHITESPACE':([5,11,],[8,13,]),'DOT':([5,],[9,]),'EQUAL':([8,12,],[11,14,]),'STRING':([13,14,],[16,16,]),'INTEGER':([13,14,],[17,17,]),'FLOAT':([13,14,],[18,18,]),'BOOLEAN':([13,14,],[19,19,]),'DATETIME':([13,14,],[20,20,]),'DATE':([13,14,],[21,21,]),'TIME':([13,14,],[22,22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'toml':([0,],[1,]),'expression':([0,6,],[2,10,]),'keyval':([0,6,],[4,4,]),'value':([13,14,],[15,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> toml","S'",1,None,None,None),
  ('toml -> expression NEWLINE expression','toml',3,'p_toml','toml_parser.py',10),
  ('expression -> COMMENT','expression',1,'p_expression','toml_parser.py',14),
  ('expression -> keyval NEWLINE','expression',2,'p_expression2','toml_parser.py',17),
  ('keyval -> IDENTIFIER WHITESPACE EQUAL WHITESPACE value NEWLINE','keyval',6,'p_keyval','toml_parser.py',21),
  ('keyval -> IDENTIFIER DOT IDENTIFIER EQUAL value','keyval',5,'p_keyval2','toml_parser.py',25),
  ('value -> STRING','value',1,'p_value','toml_parser.py',29),
  ('value -> INTEGER','value',1,'p_value2','toml_parser.py',33),
  ('value -> FLOAT','value',1,'p_value3','toml_parser.py',37),
  ('value -> BOOLEAN','value',1,'p_value4','toml_parser.py',41),
  ('value -> DATETIME','value',1,'p_value5','toml_parser.py',45),
  ('value -> DATE','value',1,'p_value6','toml_parser.py',49),
  ('value -> TIME','value',1,'p_value7','toml_parser.py',53),
]
