
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA COMMENT DOT EQUAL FALSE ID LEFT_BRACKET LEFT_CURLY_BRACKET MINUS NEWLINE NUM PLUS RIGHT_BRACKET RIGHT_CURLY_BRACKET STRING TRUE UNDERSCORE WS_CHARtoml : toml : expressiontoml : expression NEWLINE tomlexpression : key_valkey_val : key EQUAL valuekey : simple_keykey : dotted_keysimple_key : IDsimple_key : STRINGsimple_key : NUMdotted_key : simple_key DOT simple_keyvalue : STRINGvalue : NUM'
    
_lr_action_items = {'$end':([0,1,2,3,10,13,14,15,16,],[-1,0,-2,-4,-1,-3,-5,-12,-13,]),'ID':([0,10,12,],[7,7,7,]),'STRING':([0,10,11,12,],[8,8,15,8,]),'NUM':([0,10,11,12,],[9,9,16,9,]),'NEWLINE':([2,3,14,15,16,],[10,-4,-5,-12,-13,]),'EQUAL':([4,5,6,7,8,9,17,],[11,-6,-7,-8,-9,-10,-11,]),'DOT':([5,7,8,9,],[12,-8,-9,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'toml':([0,10,],[1,13,]),'expression':([0,10,],[2,2,]),'key_val':([0,10,],[3,3,]),'key':([0,10,],[4,4,]),'simple_key':([0,10,12,],[5,5,17,]),'dotted_key':([0,10,],[6,6,]),'value':([11,],[14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> toml","S'",1,None,None,None),
  ('toml -> <empty>','toml',0,'p_toml_empty','parser_toml.py',14),
  ('toml -> expression','toml',1,'p_toml_single','parser_toml.py',19),
  ('toml -> expression NEWLINE toml','toml',3,'p_toml_multiple','parser_toml.py',24),
  ('expression -> key_val','expression',1,'p_expression','parser_toml.py',29),
  ('key_val -> key EQUAL value','key_val',3,'p_key_val','parser_toml.py',34),
  ('key -> simple_key','key',1,'p_key_simple','parser_toml.py',42),
  ('key -> dotted_key','key',1,'p_key_dotted','parser_toml.py',47),
  ('simple_key -> ID','simple_key',1,'p_simple_key_unquoted','parser_toml.py',52),
  ('simple_key -> STRING','simple_key',1,'p_simple_key_quoted','parser_toml.py',57),
  ('simple_key -> NUM','simple_key',1,'p_simple_key_number','parser_toml.py',62),
  ('dotted_key -> simple_key DOT simple_key','dotted_key',3,'p_dotted_key','parser_toml.py',67),
  ('value -> STRING','value',1,'p_value_string','parser_toml.py',72),
  ('value -> NUM','value',1,'p_value_number','parser_toml.py',77),
]
